# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.cache/wt [current_project]
set_property parent.project_path Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/sources_1/new/onebit_full_adder.v
  Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/sources_1/new/fourbit_full_adder.v
  Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/sources_1/new/twos_complement.v
  Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/sources_1/new/fourbit_subtractor.v
  Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/sources_1/new/reverse_twos_complement.v
  Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/sources_1/new/full_fourbit_subtractor.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files Z:/Documents/Projects/EE2026_labs/fourbit_subtractor/fourbit_subtractor.srcs/constrs_1/new/constraints.xdc]


synth_design -top full_fourbit_subtractor -part xc7a35tcpg236-1


write_checkpoint -force -noxdef full_fourbit_subtractor.dcp

catch { report_utilization -file full_fourbit_subtractor_utilization_synth.rpt -pb full_fourbit_subtractor_utilization_synth.pb }
