set_property SRC_FILE_INFO {cfile:C:/Users/Auora/Documents/EE2026_labs/clock/clock.srcs/constrs_1/new/constraints.xdc rfile:../../../clock.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {CLOCK}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {OUTPUT}]
